### ISSUE TITLE
Deploy Prediction IO server on another node

### ISSUE THREAD

**Issue by savinay** [PredictionIO/PredictionIO#151]
I have set up a cluster to run spark while training prediction.io. However I would like to deploy it on another node in the same cluster. Can somebody guide me on how to go about this?

**Comment by pferrel** [comment]
setup pio and the template only on the other nodes, do not install the clustered services since they are already running on the node.You will never need to train on more than one node but you can launch the EventServer and deploy the prediction server if you have a load balancer in front of them. 

BTW you may get quicker answers on the user group https://groups.google.com/forum/#!forum/predictionio-user
