### ISSUE TITLE
Set pio build folder

### ISSUE THREAD

**Issue by PumpkinSeed** [PredictionIO/PredictionIO#224]
Can I set the location of the pio build/train/deploy **with a parameter**? Because I wrote an API for it and the exec command can't determine the buildable folder location.

**Comment by dszeto** [comment]
The best place for questions would be https://groups.google.com/forum/#!forum/predictionio-user.

Build is tricky because setting the working directory for SBT dynamically is not trivial.

For train and deploy, you can manually specify `engine.json` using the `-v` or `--variant` argument. You can see more details by doing `pio help`.

Would you mind sharing your specific use case?

**Comment by PumpkinSeed** [comment]
Yes, but I would rather use shell for it instead of set it manually. My solution: 
( cd /srv/recommender/recommender ; pio build )
